language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t forevermzm00/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true forevermzm00/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  # name of the application name in ElasticBeanstalk
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-719272187394"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
